<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-LIV42UR" failures="4" tests="7" name="Address_check" time="59.734" errors="0" timestamp="2021-11-23T15:31:06 EET">
  <testcase classname="fieldsvalidationtests.Address_check" name="checkNameFieldNegative" time="0.779"/>
  <testcase classname="fieldsvalidationtests.Address_check" name="checkNameFieldNegative" time="10.677">
    <failure type="java.lang.AssertionError" message="expected [no some error message , value: Aa!@#$%^&amp;amp;*()-_+=`~/\,.?&amp;gt;&amp;lt;|b /ыйієж] but found [3 no error message: special character]">
      <![CDATA[java.lang.AssertionError: expected [no some error message , value: Aa!@#$%^&*()-_+=`~/\,.?><|b /ыйієж] but found [3 no error message: special character]
at fieldsvalidationtests.Address_check.checkNameFieldNegative(Address_check.java:85)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- checkNameFieldNegative -->
  <testcase classname="fieldsvalidationtests.Address_check" name="checkNameFieldNegative" time="10.845">
    <failure type="java.lang.AssertionError" message="expected [no some error message , value: opvvcvcdufajpgsxkbfaftttficilxlfsfgseerwfrlhhonunvrvrcbexwooliovllxdsokgdmrrnopugscrrjupiwbbzxdwqcwm] but found [3 no error message: length100]">
      <![CDATA[java.lang.AssertionError: expected [no some error message , value: opvvcvcdufajpgsxkbfaftttficilxlfsfgseerwfrlhhonunvrvrcbexwooliovllxdsokgdmrrnopugscrrjupiwbbzxdwqcwm] but found [3 no error message: length100]
at fieldsvalidationtests.Address_check.checkNameFieldNegative(Address_check.java:85)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- checkNameFieldNegative -->
  <testcase classname="fieldsvalidationtests.Address_check" name="checkNameFieldNegative" time="10.667">
    <failure type="java.lang.AssertionError" message="expected [no some error message , value: 検査] but found [3 no error message: japanese]">
      <![CDATA[java.lang.AssertionError: expected [no some error message , value: 検査] but found [3 no error message: japanese]
at fieldsvalidationtests.Address_check.checkNameFieldNegative(Address_check.java:85)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- checkNameFieldNegative -->
  <testcase classname="fieldsvalidationtests.Address_check" name="checkNameFieldNegative" time="10.886">
    <failure type="java.lang.AssertionError" message="expected [no some error message , value: فحص] but found [3 no error message: arabic]">
      <![CDATA[java.lang.AssertionError: expected [no some error message , value: فحص] but found [3 no error message: arabic]
at fieldsvalidationtests.Address_check.checkNameFieldNegative(Address_check.java:85)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- checkNameFieldNegative -->
  <testcase classname="fieldsvalidationtests.Address_check" name="checkNameFieldPositive" time="5.787"/>
  <testcase classname="fieldsvalidationtests.Address_check" name="checkNameFieldPositive" time="5.748"/>
</testsuite> <!-- Address_check -->
